### ISSUE TITLE
gurunudi.ai.APIError: server_inaccessible

### ISSUE THREAD

**Issue by ElectroP** [gurulaghu/gurunudi#2]
when i am running 

from gurunudi import AI,lang
ai=AI()
corrected_text = ai.autocorrect("who is the primem inister of idnia")
print(corrected_text)

giving me gurunudi.ai.APIError: server_inaccessible error

**Comment by gurudevrao** [comment]
The server is live from today. Please try again. More APIs will be added going forward and existing ones will be further updated to increase accuracy. Feel free to post any issues.

**Comment by calee88** [comment]
Hello @gurudevrao. The server is down again.

**Comment by Harshitharaj06** [comment]
from gurunudi import AI,lang

ai=AI()
# definition=ai.define("ಕನ್ನಡ",lang.KANNADA)
# print(definition) 
Giving below error
gurunudi.ai.APIError: status_code_404

**Comment by kokilakn** [comment]
Sever is down again!
