### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by ghost** [gurulaghu/gurunudi#3]
I've tried using both, Python 2 and 3 for running this package, however, I'm getting a similar error for both. 

**ValueError: No JSON object could be decoded**

Kindly let me know what changes I should make to run the same. So far, I'm running the package in an empty python environment with just the basic functionality. 

Thank you!

**Comment by gurudevrao** [comment]
The server is live from today. Please try again and it should be working. Please post any issues you find. New functionality will be added going forward and existing models will be updated constantly to increase accuracy.
